import "./main.css";

import WebBadge from "@components/web-badge";
import WebBreadcrumbs from "@components/web-breadcrumbs";
import WebButton from "@components/web-button";
import WebCartOverview from "@components/web-cart-overview";
import WebCartModal from "@components/web-cart-modal";
import WebCartPage from "@components/web-cart-page";
import WebContainer from "@components/web-container";
import WebErrorPage from "@components/web-error-page";
import WebFeatureList from "@components/web-feature-list";
import WebFeature from "@components/web-feature";
import WebFooter from "@components/web-footer";
import WebHeader from "@components/web-header";
import WebHero from "@components/web-hero";
import WebHomePage from "@components/web-home-page";
import WebIcon from "@components/web-icon";
import WebIconButton from "@components/web-icon-button";
import WebImage from "@components/web-image";
import WebLogo from "@components/web-logo";
import WebNavigationButton from "@components/web-navigation-button";
import WebNavigationLinkButton from "@components/web-navigation-link-button";
import WebProductCard from "@components/web-product-card";
import WebProductForm from "@components/web-product-form";
import WebProductGallery from "@components/web-product-gallery";
import WebProductLightbox from "@components/web-product-lightbox";
import WebProductList from "@components/web-product-list";
import WebProductPage from "@components/web-product-page";
import WebProductQuantity from "@components/web-product-quantity";
import WebRating from "@components/web-rating";
import WebRatingStar from "@components/web-rating-star";
import WebRouter from "@components/web-router";
import WebThemeSwitch from "@components/web-theme-switch";
import WebView from "@components/web-view";
import WebGrid from "@components/web-grid";
import WebProduct from "@components/web-product";

customElements.define("web-badge", WebBadge);
customElements.define("web-breadcrumbs", WebBreadcrumbs);
customElements.define("web-button", WebButton);
customElements.define("web-cart-overview", WebCartOverview);
customElements.define("web-cart-modal", WebCartModal);
customElements.define("web-cart-page", WebCartPage);
customElements.define("web-container", WebContainer);
customElements.define("web-error-page", WebErrorPage);
customElements.define("web-feature-list", WebFeatureList);
customElements.define("web-feature", WebFeature);
customElements.define("web-footer", WebFooter);
customElements.define("web-grid", WebGrid, { extends: "ul" });
customElements.define("web-header", WebHeader);
customElements.define("web-hero", WebHero);
customElements.define("web-home-page", WebHomePage);
customElements.define("web-icon", WebIcon);
customElements.define("web-icon-button", WebIconButton);
customElements.define("web-image", WebImage);
customElements.define("web-logo", WebLogo);
customElements.define("web-navigation-button", WebNavigationButton);
customElements.define("web-navigation-link-button", WebNavigationLinkButton);
customElements.define("web-product", WebProduct);
customElements.define("web-product-card", WebProductCard);
customElements.define("web-product-form", WebProductForm);
customElements.define("web-product-gallery", WebProductGallery);
customElements.define("web-product-lightbox", WebProductLightbox);
customElements.define("web-product-list", WebProductList);
customElements.define("web-product-page", WebProductPage);
customElements.define("web-product-quantity", WebProductQuantity);
customElements.define("web-rating", WebRating);
customElements.define("web-rating-star", WebRatingStar);
customElements.define("web-router", WebRouter);
customElements.define("web-theme-switch", WebThemeSwitch);
customElements.define("web-view", WebView);

window.addEventListener("load", () => {
  const app = document.getElementById("app");
  const webRouter = document.createElement("web-router");
  webRouter.href = window.location.href;
  app?.replaceChildren(webRouter);
});